export { CalculatorPage } from './CalculatorPage/CalculatorPage.tsx'
export { NotesPage } from './NotesPage/NotesPage.tsx'
export { NotFoundPage } from './NotFoundPage/NotFoundPage.tsx'
export { WeatherPage } from './WeatherPage/WeatherPage.tsx'
export { WelcomePage } from './WelcomePage/WelcomePage.tsx'
