export { CalculatorPage } from './CalculatorPage/CalculatorPage.jsx'
export { NotesPage } from './NotesPage/NotesPage.jsx'
export { NotFoundPage } from './NotFoundPage/NotFoundPage.jsx'
export { WeatherPage } from './WeatherPage/WeatherPage.jsx'
export { WelcomePage } from './WelcomePage/WelcomePage.jsx'
